parameters:
    frontend_url: '%env(FRONTEND_URL)%'
    aws_region: '%env(AWS_REGION)%'
    aws_bucket: '%env(AWS_BUCKET)%'
    stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'
    stripe_webhook_secret: '%env(STRIPE_WEBHOOK_SECRET)%'
    twilio_account_sid: '%env(TWILIO_ACCOUNT_SID)%'
    twilio_auth_token: '%env(TWILIO_AUTH_TOKEN)%'
    twilio_phone_number: '%env(TWILIO_PHONE_NUMBER)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    aws_s3_client:
        class: Aws\S3\S3Client
        arguments:
            -   version: 'latest'
                region: '%env(AWS_REGION)%'
                credentials:
                    key: '%env(AWS_ACCESS_KEY_ID)%'
                    secret: '%env(AWS_SECRET_ACCESS_KEY)%'

    App\Service\FileUploadService:
        arguments:
            $awsRegion: '%env(AWS_REGION)%'
            $awsBucket: '%env(AWS_BUCKET)%'

    App\Service\MagicLinkService:
        arguments:
            $frontendUrl: '%env(FRONTEND_URL)%'

    App\Service\NotificationService:
        arguments:
            $twilioAccountSid: '%env(TWILIO_ACCOUNT_SID)%'
            $twilioAuthToken: '%env(TWILIO_AUTH_TOKEN)%'
            $twilioPhoneNumber: '%env(TWILIO_PHONE_NUMBER)%'

    App\Service\StripeService:
        arguments:
            $stripeSecretKey: '%env(STRIPE_SECRET_KEY)%'
            $stripeWebhookSecret: '%env(STRIPE_WEBHOOK_SECRET)%'
